### ISSUE TITLE
text file: unity (capitalization and pinyin)

### ISSUE THREAD

**Issue by LenaHenningsen** [readchina/ReadingData#188]
@duncdrum @inamoto4 @mira-gruenwald @BIGBUNNIEEEE 
I just had a glance at the text file which is growing terrifically. As we are in the business of cleaning up: I realized that the titles in English are sometimes written with capital letters, sometimes not - I would be in favor of standard rules, such as 
capital letter in the beginning of title and subtitle and all words longer 3 letters or more:
The Lost Generation: The Rustication of China's Educated Youth.
Some titles are given in English, pinyin and characters, the latter ones have no pinyin. I am fine with that. (But I guess then we could discard the pinyin lines earlier on in the data set?)

**Comment by duncdrum** [comment]
see #167 . Clean up of text is on hold until we get the new tables from #106, and #165.

**Comment by inamoto4** [comment]
Pls go ahead with this one. The question is, whether we want to follow the actual title or apply our own style sheet. I usually tried to follow the original title of the translation. Yet, in many cases we do not have a translation but translated the title ourselves. 

So, there should be a solution.

**Comment by duncdrum** [comment]
I would argue pro pinyin, since it is helpful for other processing task, even without displaying it to the user. So where it is missing we should add it. As for unifying title case capitalization I don't think the rules for that are 100% exact, so Lena's rule make sense.

**Comment by damianodamiani** [comment]
Hi everyone, we're having a meeting now with @mira-gruenwald and @HUANG0421 and we're discussing the situation with the titles. 

In the data_dictionary file in the helper folder it's clearly written that the first title of each entry ought to be in Chinese, then the second row in English, and then add a third row for Russian titles in Russian. From the previous comments by @duncdrum we also understand that a third/fourth (in the case of Russian titles) row is now to be added with pinyin.

There are a few problems with this.

First, why only add the original title in the case of Russian works? What about French, Italian, Japanese or Polish? If one language than all languages, we should be consistent throughout. Besides many titles in other languages are already added like this too.

Second, in some cases, we only give the English title without the Chinese translation, while in other is the other way around. I think we should find some clear solution to this and redo all the entries so they follow the rules.

Third, I have a problem with pinyin. Its rules are confusing and usages limited, especially given that now everyone has pop-up dictionaries anyways pre-installed in their browsers. However, were we to add pinyin to the database, we should redo all the existing entries, so that it's consistent throughout. 

These are more general questions, referring also to the way we should add names of persons, places and all other data - which languages, in what order and in what translations?

**Comment by duncdrum** [comment]
@damianodamiani there seems to be a misunderstanding:
re 1) we always add Chinese (since this is what the database is about) and english (the language of the database), in cases where the original isn't english we also add original language, russian is just an example, if its zwahili we add that. 

re 2) In principle all Chinese titles should have an english translation (either published or by us), where they are missing these need to be added (see open issues). However, especially with secondary sources, there are no Chinese translations and titles, in those case just the original or english titles suffices. If folks want to add Chinese translations there as well, I wouldn't be opposed but consider this a very low priority. Do we really need to translate a 2008 Nature article's title into Chinese?

re 3) pinyin is what it is, it makes processing a lot easier because you don't have to worry about character variant forms and different input devices. So I stick by my earlier point, even if we never display it it should stay. It really helps sino undergrads as well, so in light of the target audience thats another reason in my view to keep it.

**Comment by damianodamiani** [comment]
OK, thanks for the fast answer! Understood, we will add the original title whenever it's available and/or necessary. We will leave out obscure secondary sources for now.

I get your point about pinyin, fine with me. We need to add now another row to all entries - we decided we will do this once the transfer from the old spreadsheet is completed. For new entries, we will add the pinyin row starting from now on.

**Comment by duncdrum** [comment]
actually I would suggest focusing in finishing the transfer. We can batch process pinyin transcriptions, once we have all the titles. I ll open an issue, so to not forget.

**Comment by duncdrum** [comment]
since we sorted the main problems, we can revist capitalization and similar inconsistencies with a later revision closing for now.
